#pragma once

#include "CoreMinimal.h"
#include "DroneSimulator/Simulation/LogDebug.h"

#include "PropulsionInfo.generated.h"


struct FPropellerSimInfo;

/**
 * Information generated by the propulsion model, for a single propeller.
 */
USTRUCT(BlueprintType)
struct FPropellerPropulsionInfo
{
    GENERATED_BODY()

public:

    // In rad/s
    double angular_speed = 0.0;

    // In N
    double thrust = 0.0;

    // In N/m
    double torque = 0.0;

    // In radians
    double angle_of_attack = 0.0;

    // No unit
    TArray<double> reynolds = {};

    // 0..1
    double throttle = 0.0;

    // m/s
    double velocity_axial = 0.0;

    // m/s
    double velocity_induced = 0.0;

    FDebugLog debug_log;

    FPropellerPropulsionInfo() = default;

    FPropellerPropulsionInfo(double in_angular_speed, double in_thrust, double in_torque, double in_angle_of_attack,
        const TArray<double>& in_reynolds, double in_throttle, double in_velocity_axial, double in_velocity_induced,
        const FDebugLog& in_debug_log);

    static FPropellerPropulsionInfo from_simulation_output(const FPropellerSimInfo&, double in_throttle, const FDebugLog& in_debug_log);
};

/**
 * @struct FPropulsionInfo
 * @brief Information generated by the propulsion model, to be consumed as gameplay info.
 *
 * The propulsion model abstracts away the thrust and control logic.
 * However we want to consume some info for the gameplay, and for debugging/recording.
 * This is the info that gameplay can consume, without being coupled to the propulsion model.
 */
USTRUCT(BlueprintType)
struct FPropulsionInfo
{
    GENERATED_BODY()

public:

    UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
    bool is_valid = false;

    UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
    FPropellerPropulsionInfo front_left;

    UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
    FPropellerPropulsionInfo front_right;

    UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
    FPropellerPropulsionInfo rear_left;

    UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
    FPropellerPropulsionInfo rear_right;
};
